In [380]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf
import numpy as np
import pandas as pd

In [381]:
dataframe = pd.read_csv("train_indessa.csv")
testframe = pd.read_csv("train_indessa.csv")
dataframe =dataframe.drop(['member_id','emp_title','zip_code','addr_state','dti','batch_enrolled','sub_grade','desc','title','verification_status_joint'],axis=1)
dataframe = dataframe[0:10]
testframe =testframe.drop(['member_id','emp_title','zip_code','addr_state','dti','batch_enrolled','sub_grade','desc','title','verification_status_joint'],axis=1)
testframe = testframe[20:30]

In [382]:
# dataframe.loc[:,('nstatus')] = dataframe['loan_status'] == 0
# dataframe.loc[:,('nstatus')] = dataframe['nstatus'].astype(int)
dataframe.loc[:,('term')] = dataframe['term'].str.split('months').str[0]
dataframe.loc[dataframe.grade == 'A'  ,('grade')] = '1' 
dataframe.loc[dataframe.grade == 'B'  ,('grade')] = '2' 
dataframe.loc[dataframe.grade == 'C'  ,('grade')] = '3' 
dataframe.loc[dataframe.grade == 'D'  ,('grade')] = '4' 
dataframe.loc[dataframe.grade == 'E'  ,('grade')] = '5' 
dataframe.loc[:,('emp_length')] = dataframe['emp_length'].str.split('years').str[0]
dataframe.loc[:,('emp_length')] = dataframe['emp_length'].str.split('year').str[0]
dataframe.loc[dataframe.emp_length == "< 1 "  ,('emp_length')] = '0' 
dataframe.loc[dataframe.emp_length == "10+ "  ,('emp_length')] = '11' 
dataframe.loc[dataframe.home_ownership == "OWN"  ,('home_ownership')] = '1' 
dataframe.loc[dataframe.home_ownership == "RENT"  ,('home_ownership')] = '2' 
dataframe.loc[dataframe.home_ownership == "MORTGAGE"  ,('home_ownership')] = '3'
dataframe.loc[dataframe.verification_status == "Source Verified"  ,('verification_status')] = '1'
dataframe.loc[dataframe.verification_status == "Verified"  ,('verification_status')] = '2'
dataframe.loc[dataframe.verification_status == "Not Verified"  ,('verification_status')] = '3'
dataframe.loc[dataframe.mths_since_last_major_derog.isnull()  ,('mths_since_last_major_derog')] = '0'
dataframe.loc[dataframe.pymnt_plan == 'n'  ,('pymnt_plan')] = '1'
dataframe.loc[dataframe.purpose == 'debt_consolidation'  ,('purpose')] = '3'
dataframe.loc[dataframe.purpose == 'home_improvement'  ,('purpose')] = '2'
dataframe.loc[dataframe.purpose == 'credit_card'  ,('purpose')] = '3'
dataframe.loc[dataframe.purpose == 'major_purchase'  ,('purpose')] = '4'
dataframe.loc[dataframe.purpose == 'other'  ,('purpose')] = '5'

dataframe.loc[dataframe.mths_since_last_delinq.isnull()  ,('mths_since_last_delinq')] = '0'
dataframe.loc[dataframe.mths_since_last_record.isnull()  ,('mths_since_last_record')] = '0'
dataframe.loc[dataframe.initial_list_status == 'f'  ,('initial_list_status')] = '1'
dataframe.loc[dataframe.initial_list_status == 'w'  ,('initial_list_status')] = '0'
dataframe.loc[dataframe.application_type == 'INDIVIDUAL'  ,('application_type')] = '1'
dataframe.loc[dataframe.application_type == 'JOINT'  ,('application_type')] = '0'
dataframe.loc[:,('last_week_pay')] = dataframe['last_week_pay'].str.split('th week').str[0]


testframe.loc[:,('term')] = testframe['term'].str.split('months').str[0]
testframe.loc[testframe.grade == 'A'  ,('grade')] = '1' 
testframe.loc[testframe.grade == 'B'  ,('grade')] = '2' 
testframe.loc[testframe.grade == 'C'  ,('grade')] = '3' 
testframe.loc[testframe.grade == 'D'  ,('grade')] = '4' 
testframe.loc[testframe.grade == 'E'  ,('grade')] = '5' 
testframe.loc[testframe.grade == 'F'  ,('grade')] = '6' 
testframe.loc[:,('emp_length')] = testframe['emp_length'].str.split('years').str[0]
testframe.loc[:,('emp_length')] = testframe['emp_length'].str.split('year').str[0]
testframe.loc[testframe.emp_length == "< 1 "  ,('emp_length')] = '0' 
testframe.loc[testframe.emp_length == "10+ "  ,('emp_length')] = '11' 
testframe.loc[testframe.home_ownership == "OWN"  ,('home_ownership')] = '1' 
testframe.loc[testframe.home_ownership == "RENT"  ,('home_ownership')] = '2' 
testframe.loc[testframe.home_ownership == "MORTGAGE"  ,('home_ownership')] = '3'
testframe.loc[testframe.verification_status == "Source Verified"  ,('verification_status')] = '1'
testframe.loc[testframe.verification_status == "Verified"  ,('verification_status')] = '2'
testframe.loc[testframe.verification_status == "Not Verified"  ,('verification_status')] = '3'
testframe.loc[testframe.mths_since_last_major_derog.isnull()  ,('mths_since_last_major_derog')] = '0'
testframe.loc[testframe.pymnt_plan == 'n'  ,('pymnt_plan')] = '1'
testframe.loc[testframe.purpose == 'debt_consolidation'  ,('purpose')] = '3'
testframe.loc[testframe.purpose == 'home_improvement'  ,('purpose')] = '2'
testframe.loc[testframe.purpose == 'credit_card'  ,('purpose')] = '3'
testframe.loc[testframe.mths_since_last_delinq.isnull()  ,('mths_since_last_delinq')] = '0'
testframe.loc[testframe.mths_since_last_record.isnull()  ,('mths_since_last_record')] = '0'
testframe.loc[testframe.initial_list_status == 'f'  ,('initial_list_status')] = '1'
testframe.loc[testframe.initial_list_status == 'w'  ,('initial_list_status')] = '0'
testframe.loc[testframe.application_type == 'INDIVIDUAL'  ,('application_type')] = '1'
testframe.loc[testframe.application_type == 'JOINT'  ,('application_type')] = '0'
testframe.loc[:,('last_week_pay')] = testframe['last_week_pay'].str.split('th week').str[0]
testframe.loc[testframe.tot_coll_amt.isnull()  ,('tot_coll_amt')] = '0'
testframe.loc[testframe.tot_cur_bal.isnull()  ,('tot_cur_bal')] = '0'
testframe.loc[testframe.total_rev_hi_lim.isnull()  ,('total_rev_hi_lim')] = '0'
testframe.loc[testframe.purpose == 'major_purchase'  ,('purpose')] = '4'
testframe.loc[testframe.last_week_pay == 'NA'  ,('last_week_pay')] = '0'
testframe.loc[testframe.purpose == 'other'  ,('purpose')] = '5'

testframe

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,grade,emp_length,home_ownership,annual_inc,verification_status,...,collection_recovery_fee,collections_12_mths_ex_med,mths_since_last_major_derog,application_type,last_week_pay,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,loan_status
20,20000,20000,20000.0,60,17.86,4,9,2,96000.0,3,...,0.00,0.0,18,1,13,0.0,0,66738,27200,0
21,12400,12400,12400.0,36,6.62,1,2,1,40000.0,3,...,7.03,0.0,0,1,0,0.0,0,0,0,0
22,4200,4200,4200.0,36,17.57,4,11,3,46000.0,3,...,0.00,0.0,0,1,31,0.0,0,282808,25700,0
23,10500,10500,10500.0,36,13.66,3,7,1,60000.0,1,...,0.00,0.0,0,1,30,0.0,0,71697,14300,1
24,16000,16000,16000.0,36,7.89,1,0,2,65000.0,1,...,0.00,0.0,0,1,17,0.0,0,147448,41400,0
25,23800,23800,23800.0,60,15.61,4,4,3,70000.0,1,...,0.00,0.0,0,1,78,0.0,0,327930,43400,0
26,7200,7200,7150.0,36,12.99,3,2,1,37000.0,1,...,0.00,0.0,47,1,70,0.0,0,8589,19800,1
27,19200,19200,19175.0,36,6.62,1,1,3,250000.0,1,...,0.00,0.0,0,1,104,0.0,0,447388,33100,1
28,15000,15000,15000.0,36,6.92,1,3,3,90000.0,2,...,0.00,0.0,0,1,35,0.0,0,114298,49900,0
29,4000,4000,4000.0,36,17.57,4,2,3,20000.0,2,...,0.00,0.0,0,1,4,0.0,0,31445,10900,0

In [383]:
dataframe.loc[:]=dataframe[:].astype('float32')
dataframe

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,grade,emp_length,home_ownership,annual_inc,verification_status,...,collection_recovery_fee,collections_12_mths_ex_med,mths_since_last_major_derog,application_type,last_week_pay,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,loan_status
0,14350.0,14350.0,14350.0,36.0,19.190001,5.0,9.0,1.0,28700.0,1.0,...,0.0,0.0,74.0,1.0,26.0,0.0,0.0,28699.0,30800.0,0.0
1,4800.0,4800.0,4800.0,36.0,10.990000,2.0,0.0,3.0,65000.0,1.0,...,0.0,0.0,0.0,1.0,9.0,0.0,0.0,9974.0,32900.0,0.0
2,10000.0,10000.0,10000.0,36.0,7.260000,1.0,2.0,1.0,45000.0,3.0,...,0.0,0.0,0.0,1.0,9.0,0.0,65.0,38295.0,34900.0,0.0
3,15000.0,15000.0,15000.0,36.0,19.719999,4.0,11.0,2.0,105000.0,3.0,...,0.0,0.0,0.0,1.0,135.0,0.0,0.0,55564.0,24700.0,0.0
4,16000.0,16000.0,16000.0,36.0,10.640000,2.0,11.0,2.0,52000.0,2.0,...,0.0,0.0,0.0,1.0,96.0,0.0,0.0,47159.0,47033.0,0.0
5,15000.0,15000.0,14950.0,36.0,8.900000,1.0,2.0,3.0,120000.0,3.0,...,0.0,0.0,0.0,1.0,113.0,0.0,0.0,350619.0,29500.0,0.0
6,5000.0,5000.0,4975.0,36.0,7.900000,1.0,5.0,2.0,75000.0,1.0,...,0.0,0.0,0.0,1.0,117.0,0.0,1023.0,13272.0,55500.0,1.0
7,6000.0,6000.0,6000.0,36.0,9.170000,2.0,8.0,3.0,54000.0,3.0,...,0.0,0.0,54.0,1.0,78.0,0.0,0.0,272579.0,11800.0,0.0
8,6000.0,6000.0,6000.0,36.0,13.990000,3.0,7.0,3.0,92000.0,3.0,...,0.0,0.0,0.0,1.0,44.0,0.0,0.0,281521.0,62100.0,0.0
9,34550.0,34550.0,34550.0,60.0,17.139999,4.0,2.0,3.0,72000.0,2.0,...,0.0,0.0,0.0,1.0,52.0,0.0,0.0,76034.0,33200.0,0.0

In [384]:
testframe.loc[:] = testframe[:].astype('float32')
testframe

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,grade,emp_length,home_ownership,annual_inc,verification_status,...,collection_recovery_fee,collections_12_mths_ex_med,mths_since_last_major_derog,application_type,last_week_pay,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,loan_status
20,20000.0,20000.0,20000.0,60.0,17.860001,4.0,9.0,2.0,96000.0,3.0,...,0.00,0.0,18.0,1.0,13.0,0.0,0.0,66738.0,27200.0,0.0
21,12400.0,12400.0,12400.0,36.0,6.620000,1.0,2.0,1.0,40000.0,3.0,...,7.03,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
22,4200.0,4200.0,4200.0,36.0,17.570000,4.0,11.0,3.0,46000.0,3.0,...,0.00,0.0,0.0,1.0,31.0,0.0,0.0,282808.0,25700.0,0.0
23,10500.0,10500.0,10500.0,36.0,13.660000,3.0,7.0,1.0,60000.0,1.0,...,0.00,0.0,0.0,1.0,30.0,0.0,0.0,71697.0,14300.0,1.0
24,16000.0,16000.0,16000.0,36.0,7.890000,1.0,0.0,2.0,65000.0,1.0,...,0.00,0.0,0.0,1.0,17.0,0.0,0.0,147448.0,41400.0,0.0
25,23800.0,23800.0,23800.0,60.0,15.610000,4.0,4.0,3.0,70000.0,1.0,...,0.00,0.0,0.0,1.0,78.0,0.0,0.0,327930.0,43400.0,0.0
26,7200.0,7200.0,7150.0,36.0,12.990000,3.0,2.0,1.0,37000.0,1.0,...,0.00,0.0,47.0,1.0,70.0,0.0,0.0,8589.0,19800.0,1.0
27,19200.0,19200.0,19175.0,36.0,6.620000,1.0,1.0,3.0,250000.0,1.0,...,0.00,0.0,0.0,1.0,104.0,0.0,0.0,447388.0,33100.0,1.0
28,15000.0,15000.0,15000.0,36.0,6.920000,1.0,3.0,3.0,90000.0,2.0,...,0.00,0.0,0.0,1.0,35.0,0.0,0.0,114298.0,49900.0,0.0
29,4000.0,4000.0,4000.0,36.0,17.570000,4.0,2.0,3.0,20000.0,2.0,...,0.00,0.0,0.0,1.0,4.0,0.0,0.0,31445.0,10900.0,0.0

In [385]:
inputX = dataframe.ix[:,:34]
inputY = dataframe.loc[:,['loan_status']]
inputX_ = testframe.ix[:,:34]
inputY_ = testframe.loc[:,['loan_status']]

# inputX = np.array(inputX, dtype='float32')
# inputX

In [386]:
inputX

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,grade,emp_length,home_ownership,annual_inc,verification_status,...,recoveries,collection_recovery_fee,collections_12_mths_ex_med,mths_since_last_major_derog,application_type,last_week_pay,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim
0,14350.0,14350.0,14350.0,36.0,19.190001,5.0,9.0,1.0,28700.0,1.0,...,0.0,0.0,0.0,74.0,1.0,26.0,0.0,0.0,28699.0,30800.0
1,4800.0,4800.0,4800.0,36.0,10.990000,2.0,0.0,3.0,65000.0,1.0,...,0.0,0.0,0.0,0.0,1.0,9.0,0.0,0.0,9974.0,32900.0
2,10000.0,10000.0,10000.0,36.0,7.260000,1.0,2.0,1.0,45000.0,3.0,...,0.0,0.0,0.0,0.0,1.0,9.0,0.0,65.0,38295.0,34900.0
3,15000.0,15000.0,15000.0,36.0,19.719999,4.0,11.0,2.0,105000.0,3.0,...,0.0,0.0,0.0,0.0,1.0,135.0,0.0,0.0,55564.0,24700.0
4,16000.0,16000.0,16000.0,36.0,10.640000,2.0,11.0,2.0,52000.0,2.0,...,0.0,0.0,0.0,0.0,1.0,96.0,0.0,0.0,47159.0,47033.0
5,15000.0,15000.0,14950.0,36.0,8.900000,1.0,2.0,3.0,120000.0,3.0,...,0.0,0.0,0.0,0.0,1.0,113.0,0.0,0.0,350619.0,29500.0
6,5000.0,5000.0,4975.0,36.0,7.900000,1.0,5.0,2.0,75000.0,1.0,...,0.0,0.0,0.0,0.0,1.0,117.0,0.0,1023.0,13272.0,55500.0
7,6000.0,6000.0,6000.0,36.0,9.170000,2.0,8.0,3.0,54000.0,3.0,...,0.0,0.0,0.0,54.0,1.0,78.0,0.0,0.0,272579.0,11800.0
8,6000.0,6000.0,6000.0,36.0,13.990000,3.0,7.0,3.0,92000.0,3.0,...,0.0,0.0,0.0,0.0,1.0,44.0,0.0,0.0,281521.0,62100.0
9,34550.0,34550.0,34550.0,60.0,17.139999,4.0,2.0,3.0,72000.0,2.0,...,0.0,0.0,0.0,0.0,1.0,52.0,0.0,0.0,76034.0,33200.0

In [387]:
# LOAN_TRAINING = dataframe
# LOAN_TEST = inputY
# inputY_

In [388]:
# training_set = tf.contrib.learn.datasets.base.load_csv_with_header(
#     filename=LOAN_TRAINING,
#     target_dtype=np.int,
#     features_dtype=np.float32)
feature_columns = [tf.contrib.layers.real_valued_column("", dimension=34)]

In [389]:
classifier = tf.contrib.learn.DNNClassifier(feature_columns=feature_columns,
                                            hidden_units=[10, 20, 10],
                                            n_classes=2,
                                            model_dir="/tmp/loan2_model")
feature_columns

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_save_checkpoints_secs': 600, '_num_ps_replicas': 0, '_keep_checkpoint_max': 5, '_tf_random_seed': None, '_task_type': None, '_environment': 'local', '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f2943aefcd0>, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_task_id': 0, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_evaluation_master': '', '_keep_checkpoint_every_n_hours': 10000, '_master': ''}

[_RealValuedColumn(column_name='', dimension=34, default_value=None, dtype=tf.float32, normalizer=None)]

In [390]:
classifier.fit(x=inputX, y=inputY, steps=2000)

WARNING:tensorflow:From <ipython-input-390-1e6da7c6796c>:1: calling fit (from tensorflow.contrib.learn.python.learn.estimators.estimator) with y is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:From <ipython-input-390-1e6da7c6796c>:1: calling fit (from tensorflow.contrib.learn.python.learn.estimators.estimator) with x is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
WARNING:tensorflow:From /home/joel/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/head.py:1362: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 2001 into /tmp/loan2_model/model.ckpt.
INFO:tensorflow:loss = 0.0, step = 2001
INFO:tensorflow:global_step/sec: 764.083
INFO:tensorflow:loss = 0.0, step = 2101
INFO:tensorflow:global_step/sec: 803.342
INFO:tensorflow:loss = 0.0, step = 2201
INFO:tensorflow:global_step/sec: 812.875
INFO:tensorflow:loss = 0.0, step = 2301
INFO:tensorflow:global_step/sec: 782.614
INFO:tensorflow:loss = 0.0, step = 2401
INFO:tensorflow:global_step/sec: 766.331
INFO:tensorflow:loss = 0.0, step = 2501
INFO:tensorflow:global_step/sec: 438.862
INFO:tensorflow:loss = 0.0, step = 2601
INFO:tensorflow:global_step/sec: 501.968
INFO:tensorflow:loss = 0.0, step = 2701
INFO:tensorflow:global_step/sec: 762.579
INFO:tensorflow:loss = 7.00649e-45, step = 2801
INFO:tensorflow:global_step/sec: 799.424
INFO:tensorflow:loss = 0.0, step = 2901
INFO:tensorflow:global_step/sec: 760.925
INFO:tensorflow:loss = 7.00649e-45, step = 3001
INFO:tensorflow:global_step/sec: 807.527
INFO:tensorflow:loss = 0.0, step = 3101
INFO:tensorflow:global_step/sec: 775.228
INFO:tensorflow:loss = 0.0, step = 3201
INFO:tensorflow:global_step/sec: 785.639
INFO:tensorflow:loss = 0.0, step = 3301
INFO:tensorflow:global_step/sec: 820.257
INFO:tensorflow:loss = 0.0, step = 3401
INFO:tensorflow:global_step/sec: 795.368
INFO:tensorflow:loss = 0.0, step = 3501
INFO:tensorflow:global_step/sec: 445.881
INFO:tensorflow:loss = 7.00649e-45, step = 3601
INFO:tensorflow:global_step/sec: 409.71
INFO:tensorflow:loss = 0.0, step = 3701
INFO:tensorflow:global_step/sec: 420.011
INFO:tensorflow:loss = 7.00649e-45, step = 3801
INFO:tensorflow:global_step/sec: 758.616
INFO:tensorflow:loss = 0.0, step = 3901
INFO:tensorflow:Saving checkpoints for 4000 into /tmp/loan2_model/model.ckpt.
INFO:tensorflow:Loss for final step: 0.0.

DNNClassifier(params={'head': <tensorflow.contrib.learn.python.learn.estimators.head._BinaryLogisticHead object at 0x7f2943aef990>, 'hidden_units': [10, 20, 10], 'feature_columns': (_RealValuedColumn(column_name='', dimension=34, default_value=None, dtype=tf.float32, normalizer=None),), 'embedding_lr_multipliers': None, 'optimizer': None, 'dropout': None, 'gradient_clip_norm': None, 'activation_fn': <function relu at 0x7f295b9c3668>, 'input_layer_min_slice_size': None})

In [391]:
accuracy_score = classifier.evaluate(x=inputX_, y=inputY)["accuracy"]
print('Accuracy: {0:f}'.format(accuracy_score))

WARNING:tensorflow:From <ipython-input-391-cb34a64aafd3>:1: calling evaluate (from tensorflow.contrib.learn.python.learn.estimators.estimator) with y is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:From <ipython-input-391-cb34a64aafd3>:1: calling evaluate (from tensorflow.contrib.learn.python.learn.estimators.estimator) with x is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
WARNING:tensorflow:From /home/joel/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/head.py:1362: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
INFO:tensorflow:Starting evaluation at 2017-03-19-08:37:36
INFO:tensorflow:Finished evaluation at 2017-03-19-08:37:36
INFO:tensorflow:Saving dict for global step 4000: accuracy = 0.9, accuracy/baseline_label_mean = 0.1, accuracy/threshold_0.500000_mean = 0.9, auc = 0.5, global_step = 4000, labels/actual_label_mean = 0.1, labels/prediction_mean = 0.0, loss = 34.6955, precision/positive_threshold_0.500000_mean = 0.0, recall/positive_threshold_0.500000_mean = 0.0
WARNING:tensorflow:Skipping summary for global_step, must be a float or np.float32.
Accuracy: 0.900000

In [392]:
inputX_.loc[[23]]

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,grade,emp_length,home_ownership,annual_inc,verification_status,...,recoveries,collection_recovery_fee,collections_12_mths_ex_med,mths_since_last_major_derog,application_type,last_week_pay,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim
23,10500.0,10500.0,10500.0,36.0,13.66,3.0,7.0,1.0,60000.0,1.0,...,0.0,0.0,0.0,0.0,1.0,30.0,0.0,0.0,71697.0,14300.0

In [393]:

y = list(classifier.predict(inputX_.loc[[23]], as_iterable=True))
print('Predictions: {}'.format(str(y)))

WARNING:tensorflow:From /home/joel/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py:374: calling predict (from tensorflow.contrib.learn.python.learn.estimators.estimator) with x is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
Predictions: [0]